[package]
name = "solstone-core-sol-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
base64 = "0.22.1"
chrono = { workspace = true }
rustix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solstone-core-format = { workspace = true }
spl-core = { workspace = true }
ureq = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
nix = { workspace = true }

[lints]
workspace = true
