# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc

"""Checked-in category metadata generated by the native describe helper."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, cast

DEFAULT_MAX_EXTRACTIONS = 20


def _load_categories() -> dict[str, dict[str, Any]]:
    path = Path(__file__).with_name("category_registry.json")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError("native observe category registry must be an object")
    categories: dict[str, dict[str, Any]] = {}
    for name, metadata in payload.items():
        if not isinstance(name, str) or not isinstance(metadata, dict):
            raise RuntimeError("native observe category registry has an invalid entry")
        for field in ("description", "output", "label", "group", "context"):
            if not isinstance(metadata.get(field), str):
                raise RuntimeError(
                    f"native observe category registry entry {name!r} lacks {field!r}"
                )
        if not isinstance(metadata.get("max_output_tokens"), int):
            raise RuntimeError(
                f"native observe category registry entry {name!r} lacks max_output_tokens"
            )
        categories[name] = cast(dict[str, Any], metadata)
    return categories


CATEGORIES = _load_categories()

__all__ = ["CATEGORIES", "DEFAULT_MAX_EXTRACTIONS"]
