# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
set(PACKAGE_VERSION "1.4.357")
if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()
