#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc

"""Build the committed journal mark-derivation contract fixture."""

from __future__ import annotations

import argparse
import json
import sys
import time
import uuid
from pathlib import Path

import argon2.low_level

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from solstone.think.link.mark import _COLORS, _ICON_NAMES, _WORDS, mark_from_jid
from tests.link.test_mark import VECTORS, ReferenceVector

ARTIFACT_PATH = (
    ROOT / "solstone" / "think" / "link" / "mark_assets" / "mark_derivation_contract.json"
)
VECTOR_FIELDS = (
    "name",
    "spki_hex",
    "jid",
    "digest",
    "icon1",
    "color1",
    "color1_hex",
    "icon2",
    "color2",
    "color2_hex",
    "word1",
    "word2",
    "rot1",
    "rot2",
    "raw16",
)


def _digest_hex(jid: uuid.UUID) -> str:
    """Return the independently computed locked Argon2id digest."""
    return argon2.low_level.hash_secret_raw(
        secret=jid.bytes,
        salt=b"solstone-journal-mark-v1",
        time_cost=3,
        memory_cost=65536,
        parallelism=1,
        hash_len=32,
        type=argon2.low_level.Type.ID,
        version=0x13,
    ).hex()


def _derive_vector_record(vector: ReferenceVector) -> dict[str, object]:
    """Derive the mark fields for one recorded jid reference vector."""
    jid = uuid.UUID(vector.jid)
    mark = mark_from_jid(jid)
    return {
        "name": vector.name,
        "spki_hex": vector.spki_hex,
        "jid": str(jid),
        "digest": _digest_hex(jid),
        "icon1": mark.icon1.name,
        "color1": mark.icon1.color_name,
        "color1_hex": mark.icon1.color_hex,
        "icon2": mark.icon2.name,
        "color2": mark.icon2.color_name,
        "color2_hex": mark.icon2.color_hex,
        "word1": mark.words[0],
        "word2": mark.words[1],
        "rot1": mark.icon1.rot,
        "rot2": mark.icon2.rot,
        "raw16": vector.raw16,
    }


def _verify_against_reference(
    vector: ReferenceVector, derived: dict[str, object]
) -> None:
    """Raise on the first difference between a derived record and its oracle."""
    for field in VECTOR_FIELDS:
        expected = getattr(vector, field)
        actual = derived[field]
        if actual != expected:
            raise RuntimeError(
                f"{vector.name}: {field} mismatch: expected {expected!r}, got {actual!r}"
            )


def _verified_reference_vectors() -> list[dict[str, object]]:
    """Derive every reference vector and prove it agrees with the test oracle."""
    records: list[dict[str, object]] = []
    for vector in VECTORS:
        derived = _derive_vector_record(vector)
        _verify_against_reference(vector, derived)
        records.append(derived)
    return records


def _measure_derivation_cost() -> float:
    """Measure one primary-vector mark derivation in seconds."""
    jid = uuid.UUID(VECTORS[0].jid)
    started = time.perf_counter()
    mark_from_jid(jid)
    return round(time.perf_counter() - started, 6)


def _build_contract_payload(*, derivation_wall_seconds: float) -> dict[str, object]:
    """Return the full mark-derivation contract after proving its vectors."""
    return {
        "contract": "solstone-journal-mark-derivation",
        "rust_consumer_status": "No Rust implementation exists yet.",
        "x-journal-contract": {
            "format_id": "journal-mark-derivation",
            "schema_owner": "solstone.think.link.mark",
            "reference_writer": "solstone.think.link.mark.mark_from_jid",
            "allowed_producers": [
                "solstone.think.link.mark.mark_from_jid",
                "solstone.think.link.mark.mark_from_spki",
            ],
            "write_discipline": (
                "Computed on demand; the mark itself has no at-rest write path. "
                "This fixture is the only persisted artifact and is regenerated by "
                "scripts/build_mark_derivation_contract.py only after its proof gate "
                "against tests/link/test_mark.py:VECTORS passes; never hand-edit."
            ),
            "file_kind": "derivation-contract",
            "key_fields": [
                "derivation.argon2id",
                "derivation.digest_word_split",
                "derivation.selection_rules",
                "assets.glyphs.names",
                "assets.colors.entries",
                "assets.words",
                "reference_vectors",
            ],
            "fixture_generator": "scripts/build_mark_derivation_contract.py",
        },
        "argon2_secret_parameter_note": (
            "argon2.low_level.hash_secret_raw.__doc__ says \"Hash *password* and "
            "return a **raw** hash.\" Its sibling hash_secret documents its secret "
            "argument as \"Secret to hash.\" Therefore secret= is Argon2's "
            "password/message input P, not a keyed Argon2 secret K; this low-level "
            "API exposes no separate K parameter."
        ),
        "derivation": {
            "argon2id": {
                "input": "jid.bytes (16 UUID bytes)",
                "salt": "solstone-journal-mark-v1",
                "salt_encoding": "ASCII bytes",
                "time_cost": 3,
                "memory_cost": 65536,
                "parallelism": 1,
                "hash_len": 32,
                "type": "ID",
                "version": 19,
                "version_hex": "0x13",
            },
            "digest_word_split": {
                "digest_length_bytes": 32,
                "word_count": 7,
                "word_width_bits": 32,
                "byte_order": "big-endian",
                "source_byte_range": "digest[0:28]",
                "unused_trailing_bytes": 4,
            },
            "selection_rules": {
                "pick": "w % n",
                "pick_distinct": "i = w % (n - 1); if i >= not_i: i += 1; return i",
                "icon1": "pick(u[0], icon_count)",
                "icon2": "pick_distinct(u[1], icon_count, icon1_i)",
                "color1": "pick(u[2], color_count)",
                "color2": "pick_distinct(u[3], color_count, color1_i)",
                "word1": "pick(u[4], word_count)",
                "word2": "pick_distinct(u[5], word_count, word1_i)",
                "rot1": "u[6] & 1; 0 -> 0 degrees, 1 -> 45 degrees",
                "rot2": "(u[6] >> 1) & 1; 0 -> 0 degrees, 1 -> 45 degrees",
            },
        },
        "assets": {
            "glyphs": {
                "provenance": "solstone/think/link/mark_assets/glyphs.json",
                "count": len(_ICON_NAMES),
                "names": list(_ICON_NAMES),
            },
            "colors": {
                "provenance": "solstone/think/link/mark_assets/colors.json",
                "count": len(_COLORS),
                "entries": [list(color) for color in _COLORS],
            },
            "words": {
                "provenance": "solstone/think/link/mark_assets/words.json",
                "word_count": len(_WORDS),
                "first_word": _WORDS[0],
                "last_word": _WORDS[-1],
            },
        },
        "reference_vectors": _verified_reference_vectors(),
        "performance_observation": {
            "metric": "mark_from_jid wall-clock duration",
            "units": "seconds",
            "seconds": derivation_wall_seconds,
            "sample_count": 1,
            "aggregation": "single primary-vector derivation",
            "normative": False,
            "note": (
                "Argon2id at memory_cost=65536 is deliberately slow; expect roughly "
                "0.09 seconds per derivation, depending on host."
            ),
        },
    }


def render_contract_json(*, derivation_wall_seconds: float) -> str:
    """Render the canonical contract JSON text."""
    return json.dumps(
        _build_contract_payload(derivation_wall_seconds=derivation_wall_seconds),
        indent=2,
        sort_keys=True,
    ) + "\n"


def write_output() -> None:
    """Measure and write the contract fixture after the vector proof gate passes."""
    rendered = render_contract_json(derivation_wall_seconds=_measure_derivation_cost())
    ARTIFACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {ARTIFACT_PATH.relative_to(ROOT)}")


def check_output() -> int:
    """Check the fixture without refreshing its non-normative timing observation."""
    try:
        current = ARTIFACT_PATH.read_text(encoding="utf-8")
        payload = json.loads(current)
        seconds = payload["performance_observation"]["seconds"]
    except (FileNotFoundError, json.JSONDecodeError, KeyError, TypeError) as exc:
        print(
            f"Mark derivation contract fixture is missing or malformed: {exc}. "
            "Run: scripts/build_mark_derivation_contract.py",
            file=sys.stderr,
        )
        return 1
    if isinstance(seconds, bool) or not isinstance(seconds, int | float):
        print(
            "Mark derivation contract fixture has a non-numeric "
            "performance_observation.seconds. Run: "
            "scripts/build_mark_derivation_contract.py",
            file=sys.stderr,
        )
        return 1

    expected = render_contract_json(derivation_wall_seconds=float(seconds))
    if current != expected:
        print(
            "Mark derivation contract fixture is stale: "
            f"{ARTIFACT_PATH.relative_to(ROOT)}. Run: "
            "scripts/build_mark_derivation_contract.py",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    """Run the fixture writer or staleness check."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check generated contract output without writing it.",
    )
    args = parser.parse_args()
    if args.check:
        return check_output()
    write_output()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
