#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc

"""Conformance oracle for the active-brain durable record and its fingerprint.

`health/brain.json` is the durable state of the journal's one selected thinking
lane. It is written and validated by `think/providers/brain_state.py`, fenced by
an HMAC fingerprint over the active configuration, and read by the local runtime,
the `brain` CLI, the talent runtime and the provider-readiness surface.

Two different things are pinned here, and only one of them is a vocabulary.

**The vocabularies** are transcribed from the reference module rather than
restated, so a native reader cannot hold its own copy of a closed set. There are
five of them and three carry the same concept under different spellings, which is
exactly why none of them is written down twice.

**The fingerprint algorithm is the hazard.** `canonical_fingerprint` is
`json.dumps(sort_keys=True, separators=(",", ":"), ensure_ascii=True)` over a
recursive normalization, then sha256, then HMAC-SHA256 under a per-journal key.
Ordering and separators port by accident; **serialization does not, in three
separate ways**, and each was measured against this corpus rather than assumed:

  * dict key order — Python sorts by codepoint, Rust's `BTreeMap` by UTF-8 byte,
    and UTF-8 preserves codepoint order. Safe.
  * list order — sorted by each item's own canonical JSON text, inheriting the
    same property. Safe.
  * `separators` — a compact serializer matches. Safe.
  * **non-ASCII escaping** — `ensure_ascii` renders `é` as `é`; `serde_json`
    emits the character.
  * **non-BMP escaping** — a codepoint above the BMP escapes as a UTF-16
    *surrogate pair*: `\U0001d11e` is written `𝄞`. An implementation
    that escapes non-ASCII but emits one six-digit escape still diverges.
  * **exponent form** — Python writes `1e+22` and `1e-07`; `serde_json` writes
    `1e22` and `1e-7`.

All three produce different bytes, a different sha256, and a fingerprint that no
longer matches the one on disk. The brain's evidence is then fenced out and the
lane re-probes.

A fingerprint mismatch is not a crash and not a corruption, so nothing goes red:
the journal quietly re-enters `checking`. That is why the vectors below carry
their expected `canonical_json` verbatim as well as the digest — a native
implementation that disagrees must fail on the *string*, where the cause is
legible, rather than on a hex digest that says only "different".

⚠ Regenerating this file requires a runnable reference tree. It is a frozen
record, not a live comparison.

Determinism: every value here is a pure function of its input. The HMAC vectors
use a fixed key so the digests are reproducible; the real key is 32 random bytes
per journal and is never recorded anywhere.
"""

from __future__ import annotations

import hmac
import json
import subprocess
from pathlib import Path
from typing import Any, get_args

from solstone.think.providers import brain_state as bs
from solstone.think.providers.install_state import (
    canonical_fingerprint,
    fingerprint_sha256,
)

FIXTURE_VERSION = 1

REPO_ROOT = Path(__file__).resolve().parent.parent
# The reference modules these values were read out of. Recorded so the frozen
# record can say what it was frozen from.
REFERENCE_SOURCES = (
    "solstone/think/providers/brain_state.py",
    "solstone/think/providers/install_state.py",
)


def reference_commit(sources: tuple[str, ...] = REFERENCE_SOURCES) -> str:
    """The commit that last changed the reference this corpus was read from.

    ⚠ Deliberately **not** `HEAD`. A frozen record must be able to name the tree
    it was frozen from, but a fixture whose content moves on every unrelated
    commit cannot be checked for drift — `make check-core-fixtures` compares the
    regenerated bytes exactly, so a `HEAD` stamp turns the regeneration check
    red on the next commit to anything at all.

    Pinning the reference *sources* gets both properties: the value is stable
    while the reference is unchanged, and it moves exactly when the thing this
    corpus describes moves — at which point the check going red is the correct
    answer, because the corpus is stale.
    """
    result = subprocess.run(
        ["git", "log", "-1", "--format=%H", "--", *sources],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    commit = result.stdout.strip()
    if result.returncode != 0 or not commit:
        raise SystemExit(
            "refusing to write a corpus that cannot name its reference tree"
        )
    return commit

# A fixed key so the recorded HMAC digests are reproducible. ⛔ Not a secret and
# ⛔ never a default: the real fingerprint key is 32 bytes from `secrets` written
# to `health/brain-fingerprint.key` on first use, one per journal.
VECTOR_HMAC_KEY = bytes(range(32))


def _vector(name: str, value: Any, note: str) -> dict[str, Any]:
    """Record one canonical-fingerprint case: input, exact text, and digest."""
    canonical = canonical_fingerprint(value)
    return {
        "name": name,
        "note": note,
        # `input_json` is the case's input rendered non-canonically, so a reader
        # reconstructs the input rather than reading it back out of the answer.
        # ⚠ It is JSON, so it cannot express the two input types whose handling
        # this corpus exists to pin — a tuple and a `Path` both arrive already
        # flattened. `input_repr` is the oracle for those: a consumer holding a
        # typed path or a fixed-length sequence must read it, not `input_json`.
        "input_repr": repr(value),
        "input_json": json.dumps(_jsonable(value), ensure_ascii=False, sort_keys=False),
        "canonical_json": canonical,
        "sha256": fingerprint_sha256(canonical),
        "hmac_sha256": hmac.digest(
            VECTOR_HMAC_KEY, canonical.encode("utf-8"), "sha256"
        ).hex(),
    }


def _jsonable(value: Any) -> Any:
    """Render Path values for the input echo; the algorithm does this itself."""
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    return value


def _fingerprint_vectors() -> list[dict[str, Any]]:
    return [
        _vector(
            "ascii_flat",
            {"lane": "bundled", "active": {"provider": "local", "model": "q"}},
            "the nominal shape; proves compact separators and key sorting.",
        ),
        _vector(
            "non_ascii_value",
            {"model": "café-4b"},
            "⛔ THE FIRST DIVERGENCE. Python emits \\u00e9; serde_json emits the "
            "character. Every other case in this corpus can pass while this "
            "one fails, and a journal with a plain-ASCII config never reaches it.",
        ),
        _vector(
            "non_ascii_key",
            {"modèle": "local"},
            "the same escape on the key side, which a serializer can treat "
            "differently from values.",
        ),
        _vector(
            "astral_plane",
            {"note": "\U0001d11e clef"},
            "⛔ THE SECOND DIVERGENCE. A non-BMP codepoint escapes as a UTF-16 "
            "SURROGATE PAIR under ensure_ascii. A native implementation that "
            "escapes non-ASCII but emits one six-digit escape, or the raw "
            "character, still diverges here — so passing `non_ascii_value` is "
            "not evidence of passing this one.",
        ),
        _vector(
            "control_characters",
            {"text": 'a\nb\tc"d\\e\x00f\x1bg'},
            "the escapes both serializers agree on, recorded so a native "
            "implementation cannot pass by escaping everything.",
        ),
        _vector(
            "key_sort_order",
            {"Z": 1, "a": 2, "_": 3, "A": 4, "0": 5, "é": 6, "\U0001d11e": 7},
            "codepoint order, not any locale collation: uppercase before "
            "lowercase, '_' after uppercase, non-ASCII last.",
        ),
        _vector(
            "list_sorted_by_canonical_text",
            {"items": [{"b": 2}, {"a": 1}, [3, 1], "z", "a", 10, 9, True, None]},
            "a list is sorted by each item's own canonical JSON text, so 10 "
            "precedes 9 and `true` precedes `null` — a LEXICAL order over "
            "serialized items, never a value order.",
        ),
        _vector(
            "nested_list_normalized_before_sorting",
            {"items": [[{"b": 1, "a": 2}], [{"z": 0}]]},
            "inner values are normalized first, then the outer list is sorted "
            "on the normalized text. Sorting before normalizing gives a "
            "different order for the same input.",
        ),
        _vector(
            "tuple_becomes_list",
            {"pins": ("b", "a")},
            "tuples are normalized as lists and therefore also sorted; a "
            "positional tuple does NOT keep its order through this function.",
        ),
        _vector(
            "path_becomes_string",
            {"binary": Path("/opt/llama/llama-server"), "model": Path("m.gguf")},
            "Path is stringified. ⚠ A native implementation taking a typed path "
            "must render the same platform-native separator form.",
        ),
        _vector(
            "numbers",
            {
                "int": 42,
                "big": 9007199254740993,
                "zero": 0,
                "neg_zero_float": -0.0,
                "one_float": 1.0,
                "tenth": 0.1,
                "tiny": 1e-7,
                "huge": 1e22,
                "bool_true": True,
                "bool_false": False,
                "nil": None,
            },
            "⛔ THE THIRD DIVERGENCE, in the exponents: Python writes 1e+22 and "
            "1e-07, serde_json writes 1e22 and 1e-7. Also pins that 1.0 must not "
            "collapse to 1 and -0.0 must not collapse to 0. ⚠ No live fingerprint "
            "component carries a float today — this is here because an install "
            "pin is an arbitrary dict and the next one may.",
        ),
        _vector(
            "empty_containers",
            {"dict": {}, "list": [], "string": "", "nested": {"a": []}},
            "empty is a value, not an absence.",
        ),
        _vector(
            "stringified_keys_collide",
            {1: "int-key", "1": "str-key", True: "bool-key"},
            "🔴 a lossy, order-dependent step: 1 and True are the same Python "
            "dict key, and str() then collapses that onto '1', so one entry "
            "survives out of three. ⚠ UNREACHABLE from the live component "
            "builder, which uses string keys throughout — recorded so a native "
            "implementation REFUSES a non-string key rather than inventing a "
            "collapse rule, which is the only way it could differ silently.",
        ),
        _vector(
            "lane_bundled_shape",
            {
                "schema_version": bs.FINGERPRINT_SCHEMA_VERSION,
                "lane": "bundled",
                "active": {"provider": "local", "model": "local/qwen3.5-4b"},
                "bundled_runtime": "0" * 64,
            },
            "the real component shape for the local lane.",
        ),
        _vector(
            "lane_byo_cloud_shape",
            {
                "schema_version": bs.FINGERPRINT_SCHEMA_VERSION,
                "lane": "byo-cloud",
                "active": {"provider": "anthropic", "model": "claude"},
                "cloud_credential": "f" * 64,
            },
            "⚠ an EGRESS sibling's shape. Recorded because one record serves "
            "five lanes, not because this lane may change that sibling.",
        ),
        _vector(
            "lane_byo_endpoint_shape",
            {
                "schema_version": bs.FINGERPRINT_SCHEMA_VERSION,
                "lane": "byo-endpoint",
                "active": {"provider": "local", "model": ""},
                "local_endpoint": {
                    "base_url": "http://127.0.0.1:8080",
                    "served_model_id": "m",
                    "credential": None,
                },
            },
            "⚠ an EGRESS sibling's shape; a null credential is distinct from an "
            "absent one.",
        ),
        _vector(
            "lane_spp_shape",
            {
                "schema_version": bs.FINGERPRINT_SCHEMA_VERSION,
                "lane": "spp",
                "active": {"provider": "local", "model": ""},
                "local_endpoint": {
                    "base_url": "https://spp.example",
                    "served_model_id": "m",
                    "credential": "a" * 64,
                },
                "confidential": "b" * 64,
            },
            "⚠ an EGRESS sibling's shape; the confidential provenance digest is "
            "an HMAC of a canonicalized block, i.e. this function applied twice.",
        ),
        _vector(
            "lane_none_shape",
            {
                "schema_version": bs.FINGERPRINT_SCHEMA_VERSION,
                "lane": "none",
                "active": {"provider": "none", "model": ""},
            },
            "no engine chosen still has a fingerprint.",
        ),
    ]


def _canonical_digest_vectors() -> list[dict[str, Any]]:
    """`_canonical_digest` wraps its argument in {"value": …} before hashing.

    Recorded separately because the wrapper is invisible at the call site and a
    native implementation that hashes the bare value produces a digest that is
    wrong in a way nothing detects until an SPP provenance block changes.
    """
    cases: list[tuple[str, Any]] = [
        ("null", None),
        ("string", "café"),
        ("block", {"image": "sha256:abc", "measurement": "0" * 96}),
        ("list", [2, 1]),
    ]
    vectors = []
    for name, value in cases:
        payload = canonical_fingerprint({"value": value})
        vectors.append(
            {
                "name": name,
                "input_json": json.dumps(value, ensure_ascii=False),
                "wrapped_canonical_json": payload,
                "hmac_sha256": hmac.digest(
                    VECTOR_HMAC_KEY, payload.encode("utf-8"), "sha256"
                ).hex(),
            }
        )
    return vectors


def _sorted_literal(alias: Any) -> list[str]:
    return sorted(get_args(alias))


def _brain_vocabularies() -> dict[str, Any]:
    return {
        "schema_version": bs.SCHEMA_VERSION,
        "fingerprint_schema_version": bs.FINGERPRINT_SCHEMA_VERSION,
        "file_mode_octal": format(bs.BRAIN_FILE_MODE, "04o"),
        "fingerprint_key_bytes": bs.FINGERPRINT_KEY_BYTES,
        "checking_ttl_seconds": int(bs.CHECKING_TTL.total_seconds()),
        "default_ready_evidence_ttl_seconds": int(
            bs.DEFAULT_READY_EVIDENCE_TTL.total_seconds()
        ),
        "paths": {
            "record": "health/brain.json",
            "fingerprint_key": "health/brain-fingerprint.key",
            "refresh_lease": "health/brain-refresh.lease",
        },
        # 🔴 FIVE lanes, of which `spp`, `byo-cloud` and `byo-endpoint` are the
        # egress siblings. One record, one writer, five lanes.
        "lanes": _sorted_literal(bs.BrainLaneId),
        "lane_components": {
            lane: list(components)
            for lane, components in sorted(bs.LANE_COMPONENTS.items())
        },
        # Order is load-bearing: evidence is reduced in this sequence.
        "component_order": list(bs.COMPONENT_ORDER),
        "aggregate_states": sorted(bs.BRAIN_AGGREGATE_STATES),
        "component_statuses": sorted(bs.BRAIN_COMPONENT_STATUSES),
        # snake_case. ⚠ `runtime_phases` below is kebab-case for the same domain;
        # the translation table is the only sanctioned bridge.
        "reason_codes": _sorted_literal(bs.BrainReasonCode),
        "reason_to_aggregate": dict(sorted(bs.BRAIN_REASON_TO_AGGREGATE.items())),
        "runtime_failure_aggregates": sorted(bs.RUNTIME_FAILURE_AGGREGATES),
        "evidence_reason_codes": {
            component: sorted(codes)
            for component, codes in sorted(bs.BRAIN_EVIDENCE_REASON_CODES.items())
        },
        "projection_only_reason_codes": sorted(bs.BRAIN_PROJECTION_ONLY_REASON_CODES),
        "runtime_phases": _sorted_literal(bs.RuntimePhase),
        "runtime_reason_codes": sorted(bs.RUNTIME_REASON_CODES),
        "runtime_phase_to_reason": dict(sorted(bs.RUNTIME_PHASE_TO_REASON.items())),
        "runtime_reason_to_brain_reason": dict(
            sorted(bs.RUNTIME_REASON_TO_BRAIN_REASON.items())
        ),
        "incoherent_runtime_phase_reason_codes": sorted(
            list(pair) for pair in bs.INCOHERENT_RUNTIME_PHASE_REASON_CODES
        ),
        "runtime_transition_phases": sorted(bs.RUNTIME_TRANSITION_PHASES),
        "config_diagnostic_fields": sorted(bs.CONFIG_DIAGNOSTIC_FIELDS),
        "diagnostic_metadata_schemas": {
            code: {key: sorted(values) for key, values in sorted(schema.items())}
            for code, schema in sorted(bs.DIAGNOSTIC_METADATA_SCHEMAS.items())
        },
        # Closed field sets: an unknown field is rejected, never ignored.
        "record_fields": {
            "top_level": sorted(bs.BRAIN_TOP_LEVEL_FIELDS),
            "checking": sorted(bs.BRAIN_CHECKING_FIELDS),
            "evidence": sorted(bs.BRAIN_EVIDENCE_FIELDS),
            "evidence_component": sorted(bs.BRAIN_EVIDENCE_COMPONENT_FIELDS),
            "runtime_failure_marker": sorted(bs.BRAIN_RUNTIME_FAILURE_MARKER_FIELDS),
        },
        "cloud_byo_providers": sorted(bs.CLOUD_BYO_PROVIDERS),
        "provider_env_by_name": dict(sorted(bs.PROVIDER_ENV_BY_NAME.items())),
        "runtime_failure_components": _sorted_literal(bs.BrainRuntimeFailureComponent),
        "runtime_failure_rejected_reasons": _sorted_literal(
            bs.BrainRuntimeFailureRejectedReason
        ),
        "prerequisite_renewal_statuses": _sorted_literal(
            bs.BrainPrerequisiteRenewalStatus
        ),
        "inspection_statuses": _sorted_literal(bs.BrainInspectionStatus),
    }


def build_local_contract_fixture() -> dict[str, Any]:
    return {
        "fixture": "solstone-local-contract",
        "fixture_version": FIXTURE_VERSION,
        "generated_by": "make core-fixtures",
        "generator": "scripts/local_contract_corpus.py",
        "reference_sources": list(REFERENCE_SOURCES),
        "reference_commit": reference_commit(),
        "brain_state": _brain_vocabularies(),
        "canonical_fingerprint": {
            "algorithm": {
                "normalize": (
                    "recursive: dict keys coerced with str() then sorted; "
                    "lists and tuples normalized then sorted by each item's own "
                    "canonical JSON text; Path stringified"
                ),
                "serialize": "json, sort_keys, separators=(',',':'), ensure_ascii",
                "digest": "sha256 over the utf-8 canonical text",
                "keyed_digest": "hmac-sha256 over the utf-8 canonical text",
            },
            "vector_hmac_key_hex": VECTOR_HMAC_KEY.hex(),
            "vectors": _fingerprint_vectors(),
            "canonical_digest_vectors": _canonical_digest_vectors(),
        },
    }


if __name__ == "__main__":  # pragma: no cover - manual regeneration aid
    print(json.dumps(build_local_contract_fixture(), indent=2, ensure_ascii=False))
