#!/usr/bin/env sh
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
# Driver for one fresh, source-bound, network-denied ONNX Runtime Windows slot.
set -eu
GIT=${GIT:-git}; SCP=${SCP:-scp}; SSH=${SSH:-ssh}
WIN_REMOTE_HOST=${WIN_REMOTE_HOST:-}; EXPECTED_WIN_COMMIT=${EXPECTED_WIN_COMMIT:-}; ONNX_WINDOWS_SOURCE_ROOT=${ONNX_WINDOWS_SOURCE_ROOT:-}; ONNX_WINDOWS_MIRROR_INPUT_DIR=${ONNX_WINDOWS_MIRROR_INPUT_DIR:-}; ONNX_WINDOWS_PROTOC_ARCHIVE=${ONNX_WINDOWS_PROTOC_ARCHIVE:-}; WIN_REMOTE_HOME=${WIN_REMOTE_HOME:-'C:\Users\solbuild'}; SOLSTONE_JOURNAL_WIN_REFS_ROOT=${SOLSTONE_JOURNAL_WIN_REFS_ROOT:-'R:\'}; SOLSTONE_JOURNAL_WIN_OWNER_ACCOUNT=${SOLSTONE_JOURNAL_WIN_OWNER_ACCOUNT:-solbuild}
hex() { [ "${#1}" -eq "$2" ] && ! printf '%s' "$1" | grep -q '[^0-9a-f]'; }
[ -n "$WIN_REMOTE_HOST" ] && printf '%s\n' "$WIN_REMOTE_HOST" | grep -Eq '^[A-Za-z0-9_.@-]+$' || { echo 'ERROR: ONNX Windows build requires safe WIN_REMOTE_HOST' >&2; exit 1; }
hex "$EXPECTED_WIN_COMMIT" 40 || { echo 'ERROR: EXPECTED_WIN_COMMIT must be full lowercase commit' >&2; exit 1; }
[ -d "$ONNX_WINDOWS_SOURCE_ROOT" ] && [ -d "$ONNX_WINDOWS_MIRROR_INPUT_DIR" ] && [ -f "$ONNX_WINDOWS_PROTOC_ARCHIVE" ] || { echo 'ERROR: controlled ONNX source, mirror directory, and protoc archive are required' >&2; exit 1; }
printf '%s\n' "$WIN_REMOTE_HOME" | grep -Eq '^[A-Za-z]:[\\/][A-Za-z0-9_. ()\\/:=-]*$' || { echo 'ERROR: WIN_REMOTE_HOME must be a safe absolute Windows path' >&2; exit 1; }
printf '%s\n' "$SOLSTONE_JOURNAL_WIN_REFS_ROOT" | grep -Eq '^[A-Za-z]:[\\/][A-Za-z0-9_. ()\\/:=-]*$' || { echo 'ERROR: SOLSTONE_JOURNAL_WIN_REFS_ROOT must be a safe absolute Windows path' >&2; exit 1; }
printf '%s\n' "$SOLSTONE_JOURNAL_WIN_OWNER_ACCOUNT" | grep -Eq '^[A-Za-z0-9_.-]+$' || { echo 'ERROR: SOLSTONE_JOURNAL_WIN_OWNER_ACCOUNT must be a safe account name' >&2; exit 1; }
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd); repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd); cd "$repo_root"
[ -z "$("$GIT" status --porcelain=v1 --untracked-files=all --ignore-submodules=none)" ] || { echo 'ERROR: source-bound build requires clean Journal checkout' >&2; exit 1; }
[ "$("$GIT" rev-parse HEAD)" = "$EXPECTED_WIN_COMMIT" ] || { echo 'ERROR: HEAD does not equal EXPECTED_WIN_COMMIT' >&2; exit 1; }
input_dir="$repo_root/target/onnx-windows-inputs/$EXPECTED_WIN_COMMIT"; slot="$repo_root/target/onnx-windows-controlled-build/$EXPECTED_WIN_COMMIT"; source_archive="$input_dir/onnxruntime-source.tar.gz"; mirror_archive="$input_dir/onnxruntime-mirror.tar.gz"; cmake_archive="$repo_root/target/windows-builder-inputs/cmake-3.31.12-windows-x86_64.zip"; python_archive="$repo_root/target/windows-builder-inputs/python-3.12.10-embed-amd64.zip"
[ ! -e "$input_dir" ] && [ ! -e "$slot" ] || { echo 'ERROR: refusing to reuse ONNX input or output slot' >&2; exit 1; }
cargo run --manifest-path core/Cargo.toml -p solstone-core-distribution --bin solstone-distribution --locked -- acquire cmake-windows
mkdir -p "$(dirname "$python_archive")"; cargo run --manifest-path core/Cargo.toml -p solstone-core-distribution --bin solstone-distribution --locked -- acquire python-windows --dest "$python_archive"
mkdir -p "$input_dir"; cargo run --manifest-path core/Cargo.toml -p solstone-core-distribution --bin solstone-distribution --locked -- onnx-windows source-archive --source "$ONNX_WINDOWS_SOURCE_ROOT" --out "$source_archive"; cargo run --manifest-path core/Cargo.toml -p solstone-core-distribution --bin solstone-distribution --locked -- onnx-windows mirror-archive --source "$ONNX_WINDOWS_SOURCE_ROOT" --input-dir "$ONNX_WINDOWS_MIRROR_INPUT_DIR" --out "$mirror_archive"
cargo run --manifest-path core/Cargo.toml -p solstone-core-distribution --bin solstone-distribution --locked -- onnx-windows verify-inputs --source-archive "$source_archive" --mirror-archive "$mirror_archive" --cmake-archive "$cmake_archive" --python-archive "$python_archive" --protoc-archive "$ONNX_WINDOWS_PROTOC_ARCHIVE"
SOLSTONE_JOURNAL_WIN_REFS_ROOT="$SOLSTONE_JOURNAL_WIN_REFS_ROOT" SOLSTONE_JOURNAL_WIN_OWNER_ACCOUNT="$SOLSTONE_JOURNAL_WIN_OWNER_ACCOUNT" make win-host-ci
short_commit=$(printf '%s' "$EXPECTED_WIN_COMMIT" | cut -c 1-12); remote_rel="onnx-windows-controlled-build/$EXPECTED_WIN_COMMIT"; remote_repo="$WIN_REMOTE_HOME\\sjbuild"; remote_source="$WIN_REMOTE_HOME\\onnx-source-$EXPECTED_WIN_COMMIT.gz"; remote_mirror="$WIN_REMOTE_HOME\\onnx-mirror-$EXPECTED_WIN_COMMIT.gz"; remote_cmake="$WIN_REMOTE_HOME\\onnx-cmake-$EXPECTED_WIN_COMMIT.zip"; remote_python="$WIN_REMOTE_HOME\\onnx-python-$EXPECTED_WIN_COMMIT.zip"; remote_protoc="$WIN_REMOTE_HOME\\onnx-protoc-$EXPECTED_WIN_COMMIT.zip"; remote_slot="$WIN_REMOTE_HOME\\onnx-windows-controlled-build\\$EXPECTED_WIN_COMMIT"; remote_work="$WIN_REMOTE_HOME\\onnx-work-$short_commit"
remote_guard="if (Test-Path -LiteralPath '$remote_source') { throw 'remote ONNX source input already exists' }; if (Test-Path -LiteralPath '$remote_mirror') { throw 'remote ONNX mirror input already exists' }; if (Test-Path -LiteralPath '$remote_cmake') { throw 'remote ONNX CMake input already exists' }; if (Test-Path -LiteralPath '$remote_python') { throw 'remote ONNX Python input already exists' }; if (Test-Path -LiteralPath '$remote_protoc') { throw 'remote ONNX protoc input already exists' }; if (Test-Path -LiteralPath '$remote_slot') { throw 'remote ONNX output slot already exists' }; if (Test-Path -LiteralPath '$remote_work') { throw 'remote ONNX work root already exists' }"
"$SSH" "$WIN_REMOTE_HOST" "powershell -NoProfile -Command \"$remote_guard\""
for spec in "source:$source_archive" "mirror:$mirror_archive" "cmake:$cmake_archive" "python:$python_archive" "protoc:$ONNX_WINDOWS_PROTOC_ARCHIVE"; do name=${spec%%:*}; path=${spec#*:}; "$SCP" "$path" "$WIN_REMOTE_HOST:onnx-$name-$EXPECTED_WIN_COMMIT.$(basename "$path" | sed 's/.*\.//')"; done
remote_command="& '$remote_repo\\core\\distribution\\onnx-windows-build.ps1' -RepositoryRoot '$remote_repo' -SourceArchive '$remote_source' -MirrorArchive '$remote_mirror' -CmakeArchive '$remote_cmake' -PythonArchive '$remote_python' -ProtocArchive '$remote_protoc' -WorkRoot '$remote_work' -OutputRoot '$remote_slot\\output' -ReportRoot '$remote_slot\\report' -ExpectedProductCommit '$EXPECTED_WIN_COMMIT' -ExpectedCargoLockSha256 '$(sha256sum core/Cargo.lock | awk '{ print $1 }')' -BuilderHost '$WIN_REMOTE_HOST'"
"$SSH" "$WIN_REMOTE_HOST" "powershell -NoProfile -ExecutionPolicy Bypass -Command \"$remote_command\""
mkdir -p "$slot/output/bin" "$slot/report"; "$SCP" "$WIN_REMOTE_HOST:$remote_rel/output/bin/onnxruntime.dll" "$slot/output/bin/onnxruntime.dll"; "$SCP" "$WIN_REMOTE_HOST:$remote_rel/report/onnxruntime-build-evidence.json" "$WIN_REMOTE_HOST:$remote_rel/report/onnxruntime-build-receipt.json" "$WIN_REMOTE_HOST:$remote_rel/report/onnxruntime-build-validation.log" "$slot/report/"
cargo run --manifest-path core/Cargo.toml -p solstone-core-distribution --bin solstone-distribution --locked -- onnx-windows verify --receipt "$slot/report/onnxruntime-build-receipt.json" --output-root "$slot/output"
remote_cleanup="\$ErrorActionPreference = 'Stop'; Remove-Item -LiteralPath '$remote_source' -Force; Remove-Item -LiteralPath '$remote_mirror' -Force; Remove-Item -LiteralPath '$remote_cmake' -Force; Remove-Item -LiteralPath '$remote_python' -Force; Remove-Item -LiteralPath '$remote_protoc' -Force; Remove-Item -LiteralPath '$remote_work' -Recurse -Force; Remove-Item -LiteralPath '$remote_slot' -Recurse -Force; foreach (\$path in @('$remote_source', '$remote_mirror', '$remote_cmake', '$remote_python', '$remote_protoc', '$remote_work', '$remote_slot')) { if (Test-Path -LiteralPath \$path) { throw \"remote ONNX cleanup left path: \$path\" } }"
remote_cleanup_encoded=$(printf '%s' "$remote_cleanup" | iconv -f UTF-8 -t UTF-16LE | base64 | tr -d '\r\n')
[ -n "$remote_cleanup_encoded" ] || { echo 'ERROR: could not encode remote ONNX cleanup command' >&2; exit 1; }
"$SSH" "$WIN_REMOTE_HOST" "powershell -NoProfile -EncodedCommand $remote_cleanup_encoded"
echo "ONNX_WINDOWS_DRIVER_OK commit=$EXPECTED_WIN_COMMIT output=$slot/output/bin/onnxruntime.dll receipt=$slot/report/onnxruntime-build-receipt.json"
