// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 sol pbc
pub mod brain;
pub mod capture_health;
pub mod common;
pub mod config_dir_readable;
pub mod default_stt_ready;
pub mod disk_space;
pub mod feature;
pub mod host_dependencies;
pub mod journal_caught_up;
pub mod journal_dir_writable;
pub mod journal_leaf_exclusivity;
pub mod journal_maint_tasks;
pub mod journal_package_version;
pub mod journal_sync;
pub mod launchd_stale_plist;
pub mod local_bin_sol_reachable;
pub(crate) mod managed_wrapper;
pub mod observer_binding;
pub mod observer_delivery_stall;
pub mod observer_ingest_health;
pub mod orphan_segment_pdf;
pub mod package_metadata;
pub mod parakeet_cpp_stt_ready;
pub mod python_version;
pub mod retired_host_shim;
pub mod service_identity;
pub mod service_running;
pub mod service_status;
pub mod skill_state;
pub mod sol_importable;
pub mod speakers_analyze_installation;
pub mod stale_alias_symlink;
pub mod supervisor_conflict;
pub mod task_pace;

#[cfg(test)]
pub(crate) mod test_support;
