// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 sol pbc

pub const JOURNAL_HOST_COMMAND_COUNT: usize = 40;
pub const JOURNAL_HOST_COMMANDS: &[&str] = &[
    "backfill-processing-records",
    "backup",
    "brain",
    "config",
    "convey",
    "cortex",
    "depict",
    "describe",
    "down",
    "engage",
    "facet-candidates",
    "grab",
    "health",
    "heartbeat",
    "identity",
    "importer",
    "install-models",
    "install-provider",
    "journal-stats",
    "maintenance",
    "mcp",
    "navigate",
    "reprocess",
    "schedule",
    "segment",
    "sense",
    "service",
    "settings",
    "setup",
    "spl",
    "start",
    "streams",
    "supervisor",
    "talent",
    "think",
    "thinking",
    "top",
    "transcribe",
    "transfer",
    "up",
];
